import Head from 'next/head';
import React from 'react';
import ActivityMain from '../components/Activity/ActivityMain';
import Footer from '../components/Layout/Footer/FooterTwo/FooterTwo';
import Header from '../components/Layout/Header/Header';


export default function Activity() {

  return (
    <>
      <Head>
        <title>Craftt - Hire professionals that share your values</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <ActivityMain />
      <Footer />
    </>
  )
}
