import Head from 'next/head';
import React from 'react';
import HomeTwoMain from '../src/components/HomeTwo/HomeTwoMain';
import Footer from '../src/components/Layout/Footer/FooterTwo/FooterTwo';
import Header from '../src/components/Layout/Header/Header';


export default function HomeTwo() {

    return (
        <>
            <Head>
                <title>Craftt - Hire professionals that share your values</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header HeaderStatic="oc-transparent-header" />
            <HomeTwoMain />
            <Footer />
        </>
    )
}
